# fly.toml app configuration file generated for olivers-vpn on 2023-12-22T01:28:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "olivers-vpn"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]

[build]
  image = "ghcr.io/spotsnel/flyscale:latest"

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
